### ISSUE TITLE
Photo backup: Do not upload files multiple times and improve handling of versioning

### ISSUE THREAD

**Issue by Acranius** [Infomaniak/ios-kDrive#988]
## Workflow

There are >25'000 photos on my iPhone.
Since it takes a lot of time to back them all up, I decided not to do an initial backup, but doing some months at a time only.
By setting the date to e.g. _1 Jan 2023_, I was able to upload this year's files only.

However, when going back some months and setting the date to _1 Oct 2022_, the upload process goes through all of the photos again, including the ones that have been uploaded already.
I stopped at 01/01/2020, since the device gets rather hot during the upload, the task is tedious and the video upload takes too much time.

## Check if files are in kDrive

The photo backup should check if the files have been uploaded to kDrive already.

### Files are in kDrive

- If they are, skip the upload of those files.
- If they are, but the version stored in kDrive is an old one because the user edited the local file, replace the stored file with the new version
– I think the main behaviour should be replacing them, but might be good to let the user choose if the edited version should be added while keeping the original

Versioning is available and works great, but I'm not sure if it should be handled the default way for the photo backup process.

### Files are new

- If they are not, upload those files.

### Hide uploaded files

An option to hide already uploaded files when manually uploading files would be a nice addition, too.
That way, possible duplicates could be avoided.

### Filenames

The filenames in kDrive don't correspond with the local ones.
The formatted filenames make sense, however it is difficult to locate a file based on its "_IMG__" name.
Might make sense to add the original name as a suffix to the formatted one.

**Comment by PhilippeWeidmann** [comment]
Hi, thank you again for this detailed issue.

There is indeed an issue with the way the date setting is processed. 
When setting a date we upload ALL the pictures starting from this date even if the pictures were already uploaded (and creating a version for the already uploaded ones).

We understand that this is not logical from the user's perspective and we will only upload the new pictures (or modified ones) starting from the given date as it's done on Android. 
https://github.com/Infomaniak/android-kDrive/blob/bcebb7b8baced1d875cf3d4db48418bbbb084aa1/app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt#L272

Hiding already uploaded files from the picker in the "plus" menu can be a good idea but as the photo picker is provided by Apple we will need to investigate to see what's possible to do.

Regarding the pictures name we chose to use a date instead of the name because IMG_XXXX is limited to 10'000 elements (0 -> 9999). Appending the name to the date can be a good solution, we will discuss it internally.

**Comment by Acranius** [comment]
@PhilippeWeidmann 
Any news?

**Comment by PhilippeWeidmann** [comment]
Hi,
kDrive should now correctly handle photo assets versioning. Photos already uploaded using photo sync shouldn't be reuploaded unless they are modified. However tracking is working only for newly processed assets so some assets might be uploaded twice.

Please tell me if it's still not working for you.

**Comment by adrien-coye** [comment]
Hey,
Photo assets versioning has been in production for a while, thus I'm closing this issue.
Feel free to reopen the issue if your problem is still occurring.
